baseURL = 'https://durance123.github.io/hugonews/sh'
languageCode = 'en-us'
title = '李欣 梁岚 '
theme = 'ananke'
publishDir = "docs"

[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true